version: '3.8'

volumes:
  db: {}

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}  
      MYSQL_USER: ${DB_USER}  
      MYSQL_PASSWORD: ${DB_PASSWORD}  
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    restart: always  

  app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_ENV: local
      APP_URL: http://192.168.0.241:${DEV_PORT}  
      DB_CONNECTION: mysql  
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}  
      DB_USERNAME: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}  
      TEST_DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    ports:
      - ${DEV_PORT}:80  
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always  

  node:
    image: node:22-alpine
    working_dir: /app
    user: root
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh
    restart: always  

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT}:8025  
    restart: always  
