volumes:
  db: {}

services:
  db:
    image: mariadb:10.5  # Updated to use MariaDB image
    environment:
      MYSQL_DATABASE: ${DB_NAME}  # Use environment variable from .env
      MYSQL_USER: ${DB_USER}  # Use environment variable from .env
      MYSQL_PASSWORD: ${DB_PASSWORD}  # Use environment variable from .env
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_ENV: local
      APP_URL: http://192.168.0.241:${DEV_PORT}  # Use environment variable from .env
      DB_CONNECTION: mysql  # Keep 'mysql' since MariaDB is compatible
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}  # Use environment variable from .env
      DB_USERNAME: ${DB_USER}  # Use environment variable from .env
      DB_PASSWORD: ${DB_PASSWORD}  # Use environment variable from .env
      TEST_DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}  # Use environment variables
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    ports:
      - ${DEV_PORT}:80  # Use environment variable from .env
    volumes:
      - ./:/app
      #- ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    image: node:22-alpine
    working_dir: /app
    user: root
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT}:8025  # Use environment variable from .env
